// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: book.sql

package db

import (
	"context"
)

const addBook = `-- name: AddBook :one
INSERT INTO books (title, author_id)
VALUES ($1, $2) RETURNING id, title, author_id, created_at
`

type AddBookParams struct {
	Title    string
	AuthorID int64
}

func (q *Queries) AddBook(ctx context.Context, arg AddBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, addBook, arg.Title, arg.AuthorID)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AuthorID,
		&i.CreatedAt,
	)
	return i, err
}
