// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID   int64
	Name string
	Bio  pgtype.Text
	Uuid pgtype.UUID
}

type Book struct {
	ID        int64
	Title     string
	AuthorID  int64
	CreatedAt pgtype.Timestamptz
}
